# Generated by Django 6.1 on 2026-08-22 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('value', models.FloatField()),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'metric_name'],
                'unique_together': {('metric_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('analytics_user_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('platform', models.CharField(default='unknown', max_length=50)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_name', 'occurred_at'], name='analytics_a_event_n_aeeca0_idx'), models.Index(fields=['analytics_user_id', 'occurred_at'], name='analytics_a_analyti_09e739_idx')],
            },
        ),
    ]
