# Generated by Django 6.1 on 2026-08-21 20:02

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('commitments_due_soon', models.BooleanField(default=True)),
                ('commitments_due_now', models.BooleanField(default=True)),
                ('commitments_overdue', models.BooleanField(default=True)),
                ('goals_daily_reminder', models.BooleanField(default=True)),
                ('goals_daily_reminder_time', models.TimeField(default=datetime.time(8, 30))),
                ('goals_evening_reminder', models.BooleanField(default=True)),
                ('goals_evening_reminder_time', models.TimeField(default=datetime.time(20, 30))),
                ('quiet_hours_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(default=datetime.time(22, 0))),
                ('quiet_hours_end', models.TimeField(default=datetime.time(8, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user notification preference',
                'verbose_name_plural': 'user notification preferences',
                'db_table': 'user_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('COMMITMENT', 'Commitment'), ('GOAL', 'Goal')], max_length=32)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=64)),
                ('target_timestamp', models.DateTimeField(blank=True, null=True)),
                ('target_period', models.CharField(blank=True, default='', max_length=32)),
                ('identity_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled'), ('SUPPRESSED', 'Suppressed'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=32)),
                ('scheduled_for', models.DateTimeField()),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
                'db_table': 'reminders',
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='reminders_due_idx'), models.Index(fields=['user', 'status'], name='reminders_user_status_idx'), models.Index(fields=['entity_type', 'entity_id', 'status'], name='reminders_entity_status_idx')],
            },
        ),
    ]
