# Generated by Django 6.1 on 2026-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_reminder_claimed_at_reminder_lease_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='entity_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
