# Generated by Django 6.1 on 2026-08-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationdelivery_numeric_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='entity_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
