# Generated by Django 6.1 on 2026-08-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_reminder_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='shared_goals_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='shared_goals_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='weekly_digest_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='entity_type',
            field=models.CharField(choices=[('COMMITMENT', 'Commitment'), ('GOAL', 'Goal'), ('SYSTEM', 'System'), ('SECURITY', 'Security'), ('DIGEST', 'Digest')], max_length=32),
        ),
    ]
