# Generated by Django 6.1 on 2026-08-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_usernotificationpreferences_shared_goals_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='target_period',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
