# Generated by Antigravity for IST migration
from django.db import migrations, models


def set_default_timezone_to_ist(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(models.Q(timezone="UTC") | models.Q(timezone="")).update(timezone="Asia/Kolkata")


def reverse_set_default_timezone(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_email_verified_user_google_sub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="Asia/Kolkata", max_length=63),
        ),
        migrations.RunPython(
            set_default_timezone_to_ist,
            reverse_code=reverse_set_default_timezone,
        ),
    ]
