# Generated by Django 6.1 on 2026-08-20 05:30

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Stored lifecycle. COMPLETED and CANCELLED are terminal.', max_length=16)),
                ('timezone', models.CharField(blank=True, default='', max_length=63)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recurrence_kind', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY_DAYS', 'Weekly days'), ('N_PER_PERIOD', 'N per period')], max_length=16)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, help_text='ISO weekdays 1–7 (Mon–Sun). Empty unless WEEKLY_DAYS.')),
                ('period_unit', models.CharField(blank=True, choices=[('WEEK', 'Week')], max_length=8, null=True)),
                ('times_per_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tracking_kind', models.CharField(choices=[('BINARY', 'Binary'), ('COUNT', 'Count')], default='BINARY', max_length=8)),
                ('target_value', models.PositiveIntegerField(blank=True, null=True)),
                ('target_unit', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('AI_TEXT', 'AI text'), ('AI_SCREENSHOT', 'AI screenshot'), ('IMPORT', 'Import'), ('SYSTEM', 'System')], default='MANUAL', max_length=16)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        migrations.CreateModel(
            name='GoalCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_date', models.DateField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], max_length=16)),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_check_ins', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='goals.goal')),
            ],
            options={
                'db_table': 'goal_check_ins',
            },
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CHECKIN_RECORDED', 'Check-in recorded'), ('CHECKIN_UPDATED', 'Check-in updated')], max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_events', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='goals.goal')),
            ],
            options={
                'db_table': 'goal_events',
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['created_by', 'status'], name='goals_creator_status'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='goal_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recurrence_kind', 'DAILY'), _negated=True), models.Q(('period_unit__isnull', True), ('times_per_period__isnull', True), ('weekdays__len', 0)), _connector='OR'), name='goal_recurrence_daily'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recurrence_kind', 'WEEKLY_DAYS'), _negated=True), models.Q(('period_unit__isnull', True), ('times_per_period__isnull', True), ('weekdays__len__gte', 1)), _connector='OR'), name='goal_recurrence_weekly_days'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recurrence_kind', 'N_PER_PERIOD'), _negated=True), models.Q(('period_unit', 'WEEK'), ('times_per_period__gte', 1), ('times_per_period__lte', 7), ('weekdays__len', 0)), _connector='OR'), name='goal_recurrence_n_per_period'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('weekdays__contained_by', [1, 2, 3, 4, 5, 6, 7])), name='goal_weekdays_iso'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tracking_kind', 'BINARY'), _negated=True), ('target_value__isnull', True), _connector='OR'), name='goal_tracking_binary'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tracking_kind', 'COUNT'), _negated=True), ('target_value__gte', 1), _connector='OR'), name='goal_tracking_count'),
        ),
        migrations.AddConstraint(
            model_name='goalcheckin',
            constraint=models.UniqueConstraint(fields=('goal', 'period_date'), name='uniq_goal_check_in_period'),
        ),
        migrations.AddIndex(
            model_name='goalevent',
            index=models.Index(fields=['goal', 'created_at'], name='goals_event_created'),
        ),
    ]
