# Generated by Django 6.1 on 2026-08-20 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goal',
            name='goal_recurrence_n_per_period',
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recurrence_kind', 'N_PER_PERIOD'), _negated=True), models.Q(('period_unit', 'WEEK'), ('period_unit__isnull', False), ('times_per_period__isnull', False), ('times_per_period__gte', 1), ('times_per_period__lte', 7), ('weekdays__len', 0)), _connector='OR'), name='goal_recurrence_n_per_period'),
        ),
    ]
