# Generated by Django 6.1 on 2026-08-21 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_is_shared(apps, schema_editor):
    Goal = apps.get_model('goals', 'Goal')
    GoalParticipant = apps.get_model('goals', 'GoalParticipant')
    shared_goal_ids = GoalParticipant.objects.exclude(role='OWNER').values_list('goal_id', flat=True).distinct()
    Goal.objects.filter(id__in=shared_goal_ids).update(is_shared=True)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goalcheckin_participant_cascade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='True if goal is a shared group goal, False if personal.'),
        ),
        migrations.RunPython(backfill_is_shared, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=2000)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='goals.goal')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_goal_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goal_chat_messages',
            },
        ),
        migrations.CreateModel(
            name='GoalChatReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_read_at', models.DateTimeField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to='goals.goal')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='goals.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_chat_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goal_chat_read_states',
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['goal', 'created_at', 'id'], name='goal_chat_msg_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalchatreadstate',
            constraint=models.UniqueConstraint(fields=('goal', 'user'), name='uniq_goal_chat_user_read'),
        ),
    ]
