# Generated by Django 6.1 on 2026-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_goal_is_shared_chatmessage_goalchatreadstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='goalchatreadstate',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='goalcheckin',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='goalevent',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='goalparticipant',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
