# Generated by Django 6.1 on 2026-08-22 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_chatmessage_numeric_id_goal_numeric_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goalcheckin',
            index=models.Index(fields=['goal', 'period_date'], name='goal_checkin_goal_period_idx'),
        ),
    ]
