# Generated by Django 6.1 on 2026-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_goalcheckin_goal_checkin_goal_period_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalparticipant',
            name='invitation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CHECKIN_RECORDED', 'Check-in recorded'), ('CHECKIN_UPDATED', 'Check-in updated'), ('PARTICIPANT_INVITED', 'Participant invited'), ('PARTICIPANT_JOINED', 'Participant joined'), ('PARTICIPANT_DECLINED', 'Participant declined'), ('PARTICIPANT_LEFT', 'Participant left'), ('PARTICIPANT_REMOVED', 'Participant removed'), ('GOAL_OWNERSHIP_TRANSFERRED', 'Goal ownership transferred'), ('PARTICIPANT_REINVITED', 'Participant reinvited')], max_length=32),
        ),
    ]
