# Generated by Django 6.1 on 2026-08-28 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncActionAudit',
            fields=[
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ALREADY_PROCESSED', 'Already Processed'), ('FAILED', 'Failed')], default='APPLIED', max_length=32)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_action_audits',
                'indexes': [models.Index(fields=['user', 'processed_at'], name='sync_action_user_id_4c3ade_idx')],
            },
        ),
    ]
