# Generated by Django 6.1 on 2026-08-23 00:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMotivationQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('quote', models.TextField()),
                ('provider', models.CharField(default='gemini', max_length=64)),
                ('model', models.CharField(default='gemini-3.6-flash', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_motivation_quotes',
                'ordering': ['-date'],
            },
        ),
    ]
