# Generated by Django 6.1 on 2026-08-19 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token_hmac', models.CharField(max_length=64)),
                ('previous_token_hmac', models.CharField(blank=True, max_length=64, null=True)),
                ('previous_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('absolute_expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('logout', 'logout'), ('logout_all', 'logout_all'), ('reuse', 'reuse'), ('password_change', 'password_change'), ('admin', 'admin'), ('expired', 'expired')], max_length=32, null=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(choices=[('android', 'android'), ('ios', 'ios'), ('web', 'web'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='authenticat_user_id_dbee07_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_913824_idx')],
            },
        ),
    ]
