# Generated by Django 6.1 on 2026-08-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsession',
            name='current_refresh_secret_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
