# Generated by Django 6.1 on 2026-08-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authsession_current_refresh_secret_ciphertext'),
        ('users', '0002_rename_application_tables'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authsession',
            new_name='auth_sessio_user_id_f3b710_idx',
            old_name='authenticat_user_id_dbee07_idx',
        ),
        migrations.RenameIndex(
            model_name='authsession',
            new_name='auth_sessio_expires_81dfbf_idx',
            old_name='authenticat_expires_913824_idx',
        ),
        migrations.AlterModelTable(
            name='authsession',
            table='auth_sessions',
        ),
    ]
