# Generated by Django 6.1 on 2026-08-22 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_emailverificationtoken_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_change_tokens',
                'indexes': [models.Index(fields=['user', 'expires_at'], name='email_chang_user_id_dbbdae_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('LOGIN', 'Login'), ('GOOGLE_LOGIN', 'Google Login'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFIED', 'Email Verified'), ('GOOGLE_LINKED', 'Google Linked'), ('GOOGLE_UNLINKED', 'Google Unlinked'), ('SESSION_REVOKED', 'Session Revoked'), ('LOGOUT_ALL', 'Logout All Sessions'), ('EMAIL_CHANGE_REQUESTED', 'Email Change Requested'), ('EMAIL_CHANGED', 'Email Changed'), ('ACCOUNT_DELETION_REQUESTED', 'Account Deletion Requested'), ('NEW_DEVICE_LOGIN', 'New Device Login')], max_length=32)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(blank=True, default='', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='security_ev_user_id_c77a93_idx')],
            },
        ),
    ]
