# Generated by Django 6.1 on 2026-08-22 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_emailchangetoken_securityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='emailchangetoken',
            name='new_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('GOOGLE_LOGIN', 'Google Login'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFIED', 'Email Verified'), ('GOOGLE_LINKED', 'Google Account Linked'), ('GOOGLE_UNLINKED', 'Google Account Unlinked'), ('SESSION_REVOKED', 'Session Revoked'), ('LOGOUT_ALL', 'All Sessions Revoked'), ('EMAIL_CHANGE_REQUESTED', 'Email Change Requested'), ('EMAIL_CHANGED', 'Email Changed'), ('ACCOUNT_DELETION_REQUESTED', 'Account Deletion Requested'), ('NEW_DEVICE_LOGIN', 'New Device Login')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='platform',
            field=models.CharField(choices=[('android', 'android'), ('ios', 'ios'), ('web', 'web'), ('unknown', 'unknown')], default='unknown', max_length=16),
        ),
        migrations.AddIndex(
            model_name='emailchangetoken',
            index=models.Index(fields=['token_hash'], name='email_chang_token_h_7bcac6_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', '-created_at'], name='security_ev_event_t_33b3e5_idx'),
        ),
    ]
