from django.urls import path

from apps.authentication.views import (
    change_password,
    delete_account,
    email_change_confirm,
    email_change_request,
    google_auth,
    google_link,
    google_unlink,
    list_security_events,
    list_sessions,
    login,
    logout,
    logout_all,
    me,
    password_reset_confirm,
    password_reset_request,
    refresh,
    register,
    revoke_all_sessions_view,
    revoke_session,
    set_password,
    upload_profile_photo_view,
    delete_profile_photo_view,
    verify_email_confirm,
    verify_email_request,
)

app_name = "authentication"

urlpatterns = [
    path("register/", register, name="register"),
    path("login/", login, name="login"),
    path("google/", google_auth, name="google-auth"),
    path("google/link/", google_link, name="google-link"),
    path("google/unlink/", google_unlink, name="google-unlink"),
    path("verify-email/request/", verify_email_request, name="verify-email-request"),
    path("verify-email/confirm/", verify_email_confirm, name="verify-email-confirm"),
    path("email/change/", email_change_request, name="email-change-request"),
    path("email/change/confirm/", email_change_confirm, name="email-change-confirm"),
    path("password-reset/request/", password_reset_request, name="password-reset-request"),
    path("password-reset/confirm/", password_reset_confirm, name="password-reset-confirm"),
    path("set-password/", set_password, name="set-password"),
    path("change-password/", change_password, name="change-password"),
    path("delete-account/", delete_account, name="delete-account"),
    path("refresh/", refresh, name="refresh"),
    path("logout/", logout, name="logout"),
    path("logout-all/", logout_all, name="logout-all"),
    path("sessions/", list_sessions, name="list-sessions"),
    path("sessions/<uuid:session_id>/", revoke_session, name="revoke-session"),
    path("sessions/revoke-all/", revoke_all_sessions_view, name="revoke-all-sessions"),
    path("security-events/", list_security_events, name="list-security-events"),
    path("profile/photo/", upload_profile_photo_view, name="upload-profile-photo"),
    path("profile/photo/delete/", delete_profile_photo_view, name="delete-profile-photo"),
    path("me/", me, name="me"),
]
