# Generated by Django 6.1 on 2026-08-19 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING', 'Waiting'), ('SNOOZED', 'Snoozed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Stored lifecycle. COMPLETED and CANCELLED are terminal. OVERDUE is derived.', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('due_precision', models.CharField(choices=[('NONE', 'None'), ('DATE', 'Date'), ('DATETIME', 'Datetime')], default='NONE', help_text='NONE has no deadline. DATE is a calendar date. DATETIME is an exact time.', max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('AI_TEXT', 'AI text'), ('AI_SCREENSHOT', 'AI screenshot'), ('SHARED', 'Shared'), ('IMPORT', 'Import'), ('SYSTEM', 'System')], default='MANUAL', max_length=16)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_commitments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('COMPLETED', 'Completed'), ('SNOOZED', 'Snoozed'), ('UNSNOOZED', 'Unsnoozed'), ('WAITING', 'Waiting'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitment_events', to=settings.AUTH_USER_MODEL)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commitments.commitment')),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('RESPONSIBLE', 'Responsible'), ('RECIPIENT', 'Recipient'), ('OBSERVER', 'Observer')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active')], default='ACTIVE', max_length=16)),
                ('joined_at', models.DateTimeField()),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='commitments.commitment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['created_by', 'status', 'due_at'], name='commitments_creator_status_due'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['status', 'due_at'], name='commitments_status_due_at'),
        ),
        migrations.AddIndex(
            model_name='commitmentevent',
            index=models.Index(fields=['commitment', 'created_at'], name='commitments_event_created'),
        ),
        migrations.AddIndex(
            model_name='commitmentparticipant',
            index=models.Index(fields=['user'], name='commitments_participant_user'),
        ),
        migrations.AddConstraint(
            model_name='commitmentparticipant',
            constraint=models.UniqueConstraint(fields=('commitment', 'user'), name='uniq_commitment_participant_user'),
        ),
    ]
