# Generated by Django 6.1 on 2026-08-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0002_protect_participant_user_and_drop_redundant_index'),
        ('users', '0002_rename_application_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commitment',
            table='commitments',
        ),
        migrations.AlterModelTable(
            name='commitmentevent',
            table='commitment_events',
        ),
        migrations.AlterModelTable(
            name='commitmentparticipant',
            table='commitment_participants',
        ),
    ]
