# Generated by Django 6.1 on 2026-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0003_rename_application_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='commitmentevent',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='commitmentparticipant',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
