# Generated by Django 6.1 on 2026-08-19 20:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregate_type', models.CharField(max_length=32)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=64)),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=2048)),
            ],
            options={
                'db_table': 'outbox_events',
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True), ('next_attempt_at__isnull', False)), fields=['next_attempt_at', 'created_at'], name='outbox_unpublished_due')],
            },
        ),
    ]
