# Generated by Django 6.1 on 2026-08-19 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0001_initial_outbox_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer_group', models.CharField(max_length=128)),
                ('event_id', models.UUIDField()),
                ('processed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'processed_events',
                'constraints': [models.UniqueConstraint(fields=('consumer_group', 'event_id'), name='uniq_processed_event_group_event')],
            },
        ),
    ]
