# Generated by Django 6.1 on 2026-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0002_processed_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='aggregate_id',
            field=models.CharField(max_length=64),
        ),
    ]
