# Generated by Django 6.1 on 2026-08-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0003_alter_outboxevent_aggregate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='aggregate_id',
            field=models.UUIDField(),
        ),
    ]
